name: top3next
channels:
  - conda-forge
dependencies:
  - python=3.7.3   
  - numpy
  - matplotlib
  - gensim
  - nltk
  - tensorflow-gpu=1.13.1
  - keras
  - pytorch
  - pandas
  - pip
  - pip:
    - syft
